# NEURAL NETWORK

* One or more **_weights_** that we multiply by the **_input_** data to make a **_prediction_**:   
  * input variables = *information*
  * weights = *knowledge*
  * predictions = *outputs*   
  **Uses *knowledge* in the weights to interpret the *information* in  the input data**
  
  
* How it learns: trial and error
  * makes a prediction
  * checks if prediction is too low or too high
  * adjust the weights (up or down)
  * to predict more accurately next time it sees the same input
  
  
* Weights:
  * are initialized manually (hard-coded)
  * can make input bigger (0.85\*2) or smaller (0.85\*0.01)   
  = act like **_volume knobs_** to the input variables

# Multiple inputs
  * Combine multiple forms of information to make better informed predictions
  * Ex. predict win or loss based on 3 variables:    
  A='nb of toes', B='nb of fans' and C='win/loss records'
  * Initialize a weight for each variable
  * Prediction = weighted sum of the input   
  = **dot product** = `A*weight_A + B*weight_B + C*weight_C`   
  a measure of **similarity** between 2 vectors   
  similar to logical **`AND`**
  * Input is a **vector** of size 3 (1 value for each variable)   
  Weights is also a vector of size 3 (1 weight for each variable), aligned with the input vector

In [1]:
import numpy as np

def neural_network(input, weights):
    pred = input.dot(weights)  # vector * vector
    return pred

weights = np.array([0.1, 0.2, 0])

toes  = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

# input is every entry for the first game of the season
input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


# Multiple outputs

* Input: win/loss record
* Outputs:
  * team won or lost
  * whether players are happy or sad
  * percentage of team members who are hurt
* Predictions = a vector = multiply each weight by the input value

In [9]:
import numpy as np

def neural_network(input, weights):
    pred = weights * input  # matrix * scalar
    return pred

weights = np.array([0.3, 0.2, 0.9])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])

# input is every entry for the first game of the season
input = wlrec[0]
pred = neural_network(input, weights)
print(pred)

[0.195 0.13  0.585]


# Multiple inputs and outputs

* A weight connects each input node to each output node:
  * 3 weights out of each input node (one to each output node)
* Performs 3 independent weighted sums (dot products) to make 3 predictions
* Output = a vector

In [7]:
import numpy as np

def neural_network(input, weights):
    pred = weights.dot(input)
    return pred

                #toes - #win - #fans
weights = np.array([ [0.1, 0.1, -0.3],     # hurt?
                     [0.1, 0.2, 0.0],      # win?
                     [0.0, 1.3, 0.1] ])    # sad?

toes  = np.array([8.5,  9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2,  1.3, 0.5, 1.0])

# input is every entry for the first game of the season
input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(input)
print(pred)

[8.5  0.65 1.2 ]
[0.555 0.98  0.965]


In [9]:
pred = (8.5*0.1)+(0.65*0.1)+(1.2*0.0)
print(pred)

0.915


# Predicting on predictions

* Stacked networks
* Each layer its vector or matrix or weights
* Input of a layer is output of previous layer

In [31]:
import numpy as np

def neural_network(input, weights):
    hid = weights[0].dot(input)  # hidden set of weighted sums
    pred = weights[1].dot(hid)   # output set of weighted sums
    return pred

                      #toes - %win - #fans
ih_weights = np.array([ [0.1, 0.2, -0.1],    # hid[0]
                        [-0.1, 0.1, 0.9],    # hid[1]
                        [0.1, 0.4, 0.1] ])   # hid[2]

                      # hid[0] - hid[1] - hid[2]
hp_weights = np.array([ [0.3, 1.1, -0.1],    # hurt?
                        [0.1, 0.2, 0.0],     # win?
                        [0.0, 1.3, 0.1] ])   # sad?

weights = [ih_weights, hp_weights]

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

# input is every entry for the first game of the season
input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

[0.4595 0.145  0.5065]


# Summary

* **_forward propagation_**: nn takes input data and makes a prediction
* Prediction is based on several simple techniques repeated/stacked
* Next chapter:
  * how to set the weights so nn makes accurate predictions
  * **_weight learning_**, series of simple techniques combined many times accross an architecture