Latest innovations: speech recognition, machine translation, transformers>embeddings  

# 1. BUILDING

### Shallow NN
1 hidden layer (logistic regression)   

### Deep NN
more than 1 hidden layers  
first layers: learn low level features (common to all related tasks) -> simple tasks   
last layers: learn high level features -> complex tasks  
ex: audio signal -> phonemes -> words -> sentences   

### Standard NNs 

### Convolutional NNs  

### Recurrent NNs  

### Structured data
supervised lrng  

### Unstructured data
audio, img  

### Logistic Regression
binary classification   

### Linear Regression  

### Deep Learning
Learn the parameters that minimize the error  

### Training in Deep Learning  
  modifiy the parameters (w, b...) in order to minimize the cost function  

### Parameters     
  - weight (w)  
  - bias (b)  

### Hyperparameters   
  they control the parameters and determine their final value   
  - learning rate (alpha)   
    - if alpha too large, we may overshoot the optimal value  
    - if alpha too small, too many iterations to converge  
    tuning = plot the curve with various values  
    **See** ai specialization course 1 'w2-002-logistic-regression-with-nn'  
  - regularization parameter (lambda)  
    tuning = use the dev set   
  - number of iterations   
  - number of hidden layers
  - number of hidden units
  - choice of activation functions
  - momentum
  - mini-batch size

### Learning rate
- indicate at which pace the weights get updated   
- methods:
  - Adam (most popular)
  - adaptive learning rates:
    - Momentum
    - RMSProp
    - Adam

### Hyperparameters tuning     
deep learning = empirical process   
trying different values of hyperparameters and plotting (nb iterations * cost J) to find the best curve    
best values for a given problem can change in time (cpu, data update...)   

### Loss function: 
cost for one example  
- **L1** loss function  
- **L2** loss function
 
### Cost function: 
  average loss functions for all examples = `J(w,b)` surface of the curve  

### Gradient Descent algorithm: 
update w and b  

###  Derivative/Slope 
  (partial derivative = J function of 2+ args): height/width   
  for any value of a, if you nudge it by a certain amount, the slope will be ~
  Derivatives at each step are used to compute derivatives at following steps  

### Computation Graph: 
  organizes the computations:  
  1. Initialize parameters / Define hyperparameters: nn architecture  
  2. Loop for num_iterations:   
    a. Forward propagation: compute output (linear->activation)   
    b. Compute cost function   
    c. Backward propagation: compute gradients/derivatives using cost   
    d. Update parameters: gradient descent, using parameters, and grads from backprop    
  4. Predict: use trained parameters to predict labels
  **See** ai specialization course 1 'w2-002-logistic-regression-with-nn' + exos c1w4

### Chain rule  
  in backpropagation, if we change a, we change z, so we change J  

### Backpropagation  
[coursera ai: backpropagation](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/6dDj7/backpropagation-intuition-optional).  
  compute the derivative of the final output with respect to some other variable usually called ´dvar´ in code  

### Vectorization  
  whenever possible, avoid explicit ´for´ loops  

### Broadcasting in Python  
  https://numpy.org/doc/stable/user/basics.broadcasting.html  

### Softmax   
  normalizing function used when algorithm needs to classify two or more classes    

### Hidden
not observed, not seen in the training set

### Activation functions
[coursera ai: activation functions](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/4dDC1/activation-functions)    
[coursera ai: nns-non-linear-activation-functions](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/OASKH/why-do-you-need-non-linear-activation-functions): why do nns need non-linear activation functions   
   -> because the nn would just be outputing a linear function of the input   
   = standard linear regression.   
linear activation function: g(z) = z -> outputs the input  
[coursera ai: derivatives of activation functions](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/qcG1j/derivatives-of-activation-functions)   
  -> output values based on possible input values (max, min, 0)     
    
can be different for different layers in the same nn
- **sigmoid**: [0..1] -> only better for binary classification (0 or 1)  
- **tanh**: hyperbolic tangent [-1..1] -> 0 mean. always better for hidden layers. makes learning easier for the next layer  
- **relu**: [1 or 0 (or 0,00000000000x)] *most used* -> faster learning of all  
- **leaky relu**:  

### Initialization
[coursera ai: random initialization](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/XtFPI/random-initialization).   
- **weights**: do not initialize with zeros -> all hidden units are symmetric, they all compute the same function. initialize with random values instead.   
`np.random.randn((2,2)) * 0.01`   # '* 0.01' initializes to very small values   
if weights too large, GD will be very slow (values in the flat parts of the activation functions)  
- **bias**: can be initialized with zeros, as long as weights are note   

# 2. OPTIMIZING NEURAL NETWORKS

**!!! READ**: [deeplearning.ai: Initialization + Optimization](https://www.deeplearning.ai/ai-notes/)

## Mismatch train/test distribution
 - training = cat picture from web pages               -> high res
 - test set = cat pictures from users using your app   -> blurry

## Bias/Variance tradeoff
 (Optimal/human error = 0% - always compare to optimal error)   
 Training error: Tells you how much fitting is done, and if you have a bias problem  
 How much higher is error on dev set compared to training set tells you how bas is the variance problem    
 In the past, reducing bias always led to more variance, and reducing variance always let to more bias, so we had to choose   
 Now we have the tools to drive down one without hurting the other much       
  
 - **high variance** = too much flexibility
   - train set error 1%
   - dev set error 11%   
 -> doing well on train set but poorly on dev set, not generalizing well, curve with too much flexibility
 - SOLUTION: get more data, regularization, change network architecture      
    
      
 - **high bias** = underfitting   
   - train set error 15%
   - dev set error 16%   
 -> not fitting the training set   
 - SOLUTION: bigger network, train longer, change network architecture  
    
      
 - **high bias + high variance** 
   - train set error 15%
   - dev set error 30%   
 -> worst case scenario
    
      
 - **low bias + low variance** 
   - train set error 0.5%
   - dev set error 1%   
 -> best case scenario. 

### Optimal (Bayes) error:
base assumption on human error. 0%   
can change when even human can't judge (blurry images).  

# 2.1. Standardization

- substract the mean of the whole numpy array from each example,     
- and then divide each example by the standard deviation of the whole numpy array  
- ex: `train_set_x = train_set_x_flatten/255`  

# 2.2. Regularization

- **Why it reduces overfitting**:   
  - prevents weight matrices from being too large
  - if `lambda` very big   
  => `W` very small & zero out the impact of lots of hidden neurons    
  => `z` very small   
  - and nn becomes ***smaller and simpler***
  - takes you closer to underfitting
  - when `z` small, function is linear (see picture curve), only becomes less linear with larger values of z
    
     
- **First** focus on finding a good algorithm, **then** correct overfitting
- `W` is usually very high dimension, while `b` is just a scalar, so don't bother regularizing `b`
- **lambd**: the regularization parameter, is set using the dev set    

- **L2** regularization -> more often used, also called ***weight decay***   
= multiplying the weight matrix by numbers sligthly less than 1.  
cours 2 week 1 exo 2: 
  - L2 regularization makes your decision boundary smoother. If  λ  is too large, it is also possible to "oversmooth", resulting in a model with high bias   
  - L2-regularization relies on the assumption that a model with small weights is simpler than a model with large weights. Thus, by penalizing the square values of the weights in the cost function you drive all the weights to smaller values. It becomes too costly for the cost to have large weights! This leads to a smoother model in which the output changes more slowly as the input changes
  - Weights end up smaller ("weight decay"): Weights are pushed to smaller values   
  
  
- **L1** regularization -> W becomes sparse 
- **Data augmentation**      
- **Dropout** regularization
- **Weight regularization**:
  - LASSO
  - Ridge
  - ElasticNet
- **Early stopping**: stops the training process as soon as the validation loss reaches a plateau or starts to increase
  - **orthogonalization**
  -> good alternative = use L2 and train for as long as possible

### Dropout regularization

- Each training example is trained on a different smaller network:
  - different units dropped for each training example
  - and for each training example, different units dropped at each iteration
- Prevents from putting too much weight on some features: inputs can be randomly eliminated, so training can't rely on any one feature, so has to spead out weights   
  -> **no overfitting**   
   
    
- **Method**:
  - for each training example
    - go through each layer of the nn
      - for each node in a layer, compute the probability that it can be dropped out (random)
      - then remove all those nodes   
      -> much smaller nn
    - then do backpropagation = training this one example with the smaller network
  - for next training example, do the same:
    - compute probas -> drop nodes -> backpropagation -> training   
  
  
- **Implementation**:
  - ***inverted dropout*** technique (cf. screenshots) -> by for most used today
  - `keep_prob = 0.2` -> reduce layers by 20%   
  - can be set differently for each layer, or not applied to some layers:
    - big layers -> big weight matrices -> higher keep_prob
    - layers with more risk of overfitting -> lower keep_prob     
   
   

- Better to deactivate it during **optimization**, when plotting cost function (keep_prob=1) (cf. explanation: Course 2 Week 1 Understanding Dropout)     
  - **First** focus on finding a good algorithm, **then** correct overfitting
- Do not use at **test time**: you don't want your output to be random
  - if you want to do it: run prediction process many times with different units dropped randomly at each time and average accross them   
  -> computationally inefficient and gives roughly the same results

# 2.3. Optimization

## 2.3.1. Normalization  

- **speed up training**. 
  - same variance for all features (all features on similar small scales)   
  -> cost function more symmetric   
  -> faster and easier to optimize
- divide each row or `x` by its norm `𝑥 / ‖𝑥‖`  
- increases performance because **gradient descent converges faster**  
- https://stats.stackexchange.com/questions/211436/why-normalize-images-by-subtracting-datasets-image-mean-instead-of-the-current    
   
   
- 2 steps:
  1. subtract the mean (mu)
  2. normalize variances (sigma_^)   
- **cf screenshot** course 2 week 1 Normalizing inputs: variance of x1 and x2 both equal to 1
- use same values to normalize test set (mu and sigma_^)   
-> all data must go throught the same transformations


## 2.3.2. Vanishing/Exploding gradients

- **Exploding**: activation values ***grows*** exponentially as a function of the number of layers
- **Vanishing**: activation values ***decreases*** exponentially as a function of the number of layers  
  
  
-> GD tiny little steps -> training very long   
was for a long time a barrier for training deep learning
  
   
- **SOLUTION** (partial): better choice of random initialization

## 2.3.3. Weight initialization

- prevents vanishing/exploding gradients
   
   

- Set the variance of `W[l]` to be equal to `1/n`, or `2/n` with ReLU   
  -> all input features are mean 0 and variance 1  
  -> weights not too much bigger than 1 and not too much less than 1   
  -> `Z` on the same scale   
  -> doesn't completely solve the problem but helps prevent it    
  
  
- To do that, we initialize the weights:   
     `W[l] = np.random.randn(shape) * np.sqrt(1 / n[l-1])`    
      
    `n[l-1]` number of neurons in the previous layers, number of neurons being fed in each unit of current layer   
    
    
- Variants:
  - with ReLU: `np.sqrt(2 / n[l-1])`
  - with tanh: `np.sqrt(2 / n[l-1])` = Xavier initialization
  - `np.sqrt(2 / (n[l-1] + n[l]))`
  
  
- **Cours 2 Week 1 Exo 1**: He et al., 2015. (If you have heard of "Xavier initialization", this is similar except Xavier initialization uses a scaling factor for the weights  W[l]W[l]  of sqrt(1./layers_dims[l-1]) where He initialization would use sqrt(2./layers_dims[l-1]).)

## 2.3.4. Numerical approximation of gradients

- Compute the slope not just using a point after, but using a point after `θ + ε` and a point before `θ - ε` with same distance to current point `θ`  
   
   `[f(θ + ε) + f(θ - ε)] / 2 * ε`
   
  instead of:   

   `[f(θ + ε) / ε`

## 2.3.5. Gradient Checking

- Used during the backpropagation: compares the value of the *analytical gradient* to the *numerical gradient* at given points and plays the role of a ***sanity-check for correctness***   
   
   
- [Gradient Checking implementation](https://www.coursera.org/learn/deep-neural-network/lecture/6igIc/gradient-checking-implementation-notes)  
  - do not use at training, only at debut
  - does not work with dropout, so deactivate dropout (`keep_dims = 1.0`)
  - analysis...
  
  
- Concatenate all parameters into a giant flat vector:  
  `θ` = `W[1] b[1] ... W[L] b[L]`   
  
  
- Do the same with derivatives:   
  `d_θ` = `d_W[1] d_b[1] ... d_W[L] d_b[L]`   
  
  
- **Question**: Is   `d_θ` the gradient of the cost function `J(θ)`?
  
  - compute:
   
    ```
    for each i:
      d_θ_approx[i] = [J(θ_1 ... tθ_i + ε ...) + J(θ_1 ... θ_i - ε ...)] / (2 * ε)
    ```   
  
  - Check if `d_θ_approx[i]` is equal to `d_θ[i]` (euclidean distance)
  - Result should be equal to the value set for `ε`
  - Otherwise, check visualization of data to find data points for which value is much higher or lower = incorrect derivative computation

## 2.3.6. Optimization algorithms

- Used to train NNs much faster

### 2.3.6.1. Mini-batch gradient descent
[coursera ai: c2 w2 Mini-batch GD](https://www.coursera.org/learn/deep-neural-network/lecture/qcogH/mini-batch-gradient-descent)

[coursera ai: c2 w2 Understanding mini-batch GD](https://www.coursera.org/learn/deep-neural-network/lecture/lBXu8/understanding-mini-batch-gradient-descent)

- Batch GD = process the entire training set all at the same time = one batch
- Mini-batch GD = process mini-batches at the same time:    
  forward propagation -> cost function -> backpropagation -> weights update     
  = **much faster** because GD larger steps (vectorization)
- 5.000.000 training examples, mini-batches of 1.000   
  - = 5.000 mini-batches: `[X{1}, X{2}...]`
  - mini-batch `t: X{t}, Y{t}` with `X{t}.shape = (Mx, 1000)` and `Y{t}.shape = (Mx, 1)`
- mini-batch size: between 2 and m (nb trng ex), not too large or too small    
  see coursera 'Understanding mini-batch GD' :
  - shuffle training data before splitting into mini-batches
  - 64, 128, 256, 512, 1024...
  - fits in CPU/GPU memory
  - try different values to find the one that makes GD the more efficient  
- With a well-turned mini-batch size, usually it outperforms either gradient descent or stochastic gradient descent (particularly when the training set is large)
- Shuffling and Partitioning are the two steps required to build mini-batches
- Powers of two are often chosen to be the mini-batch size, e.g., 16, 32, 64, 128.
  
  
- **Stochastic gradient descent**: 
  - Each training example is its own mini-batch, i.e. mini-batch size = 1    
  - You use only 1 training example before updating the gradients
  - When the training set is large, SGD can be faster. But the parameters will "oscillate" toward the minimum rather than converge smoothly  
   
   
- **Batch GD**:mini-batch size = m (nb trng ex)

### 2.3.6.2. Exponentially Weighted (Moving) Averages

- Faster than mini-batch GD

### 2.3.6.3. Gradient Descent with Momentum
 - Faster than standard GD
 - Speeds up GD when oscillations high vertically and small horizontally
 - Oscillating steps: ***smaller vertically and larger horizontally***   
   = slows down learning in vertical direction + speeds it up in horizontal direction   
   -> faster!
 - See **implementation details** in the course
    
     
 - **Momentum** takes into account the **past gradients** to smooth out the update. We will store the 'direction' of the previous gradients in the variable  `v` . Formally, this will be the ***exponentially weighted average of the gradient on previous steps***. You can also think of  `v`  as the **velocity** of a ball rolling downhill, building up **speed (and momentum)** according to the direction of the gradient/slope of the hill.
  
  
- The velocity is initialized with zeros. So the algorithm will take a few iterations to "build up" velocity and start to take bigger steps.
- If  β=0β=0 , then this just becomes standard gradient descent without momentum
  
  
- **How do you choose `β`:**
  - The larger the momentum `β` is, the smoother the update because the more we take the past gradients into account. But if `β` is too big, it could also smooth out the updates too much.
  - Common values for `β` range from `0.8` to `0.999`. If you don't feel inclined to tune this, `β=0.9`  is often a reasonable default.
  - Tuning the optimal `β` for your model might need trying several values to see what works best in term of reducing the value of the cost function `J`.
  
  
- Momentum takes past gradients into account to smooth out the steps of gradient descent. It can be applied with batch gradient descent, mini-batch gradient descent or stochastic gradient descent.
- You have to tune a momentum hyperparameter  ββ  and a learning rate  α

### 2.3.6.4. RMSProp

 - Speeds up GD when oscillations high vertically and small horizontally
 - Oscillating steps: ***smaller vertically and larger horizontally***   
   = slows down learning in vertical direction + speeds it up in horizontal direction   
   -> faster!

### 2.3.6.5. Adam Optimization: Adaptive Momentum Estimation
course 2 week 2

- **Combination of Momentum and RMSProp**:
  - Compute `dW`, `db` using current mini-batch
  - Compute Momentum: `V_dW` and `V_db` (parameter `beta1`)
  - Compute RMSProp: `S_dW` and `S_db` (parameter `beta2`)
  - Compute bias correction
  - Update `W` and `b`  
  
  
- **Parameters**:
  - `alpha`: learning rate, to be tuned
  - `beta1`: default `0.9` (inventors recommendation)
  - `beta2`: default `0.999` (inventors recommendation)
  - `ε`: `10^-8` (inventors recommendation, doesn't matter much, not effect on perf)  
   
   
- **How does Adam work**:
  - It calculates an exponentially weighted average of past gradients, and stores it in variables  vv  (before bias correction) and  vcorrectedvcorrected  (with bias correction).
  - It calculates an exponentially weighted average of the squares of the past gradients, and stores it in variables  ss  (before bias correction) and  scorrectedscorrected  (with bias correction).
  - It updates parameters in a direction based on combining information from "1" and "2"
  
    
- Works well with deep learning problems and a very wide variety of architectures
- Works with mini-batch GD

### 2.3.6.6. Learning Rate Decay

= Slowly reduce the learning rate over time
  
   
- **Parameters**: 
  - `alpha0`
  - `decay_rate`
  
  
- **Method 1**:
  - `alpha0 = 0.2` and `decay_rate = 1`
  - `alpha = (1 / (1 + decay_rate * epoch_num)) * alpha0`
  - epoch 1: `alpha = 0.1`   
    epoch 2: `alpha = 0.67`   
    epoch 3: `alpha = 0.5`   
    epoch 4: `alpha = 0.4`... 
    -> plot (alpha * epoch_num) (x, y)  
    
    
- Other methods:
  - exponential learning rate decay: `alpha = 0.95^epoch_num * alpha0`
  - discrete staircase
  - etc.
  - manual decay (small number of models)

### 2.3.6.7. Local optima

- bad optima
- saddle point
- convex or concave like functions
- problem of plateaus = derivative close to 0 for a long time   
  -> GD very long slow path to get off the plateau towards optimum
  
-> can be avoided with optimization algorithms seen before

# Get your dimensions right

[coursera ai: getting your dimensions right](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/Rz47X/getting-your-matrix-dimensions-right)

In [2]:
import numpy as np

# --- Rank 1 arrays (value,)
a = np.random.randn(5)
print(a.shape)
print(a.T)                # a and a.T are the same
print(np.dot(a, a.T))     # value

# --- Column vectors: (value, 1) - Row vectors: (1, value)
print("")
a = np.random.randn(5,1)  # 5*1 matrix
print(a)
print(a.T)                # inversed shape
print(np.dot(a, a.T))     # vector
assert(a.shape == (5,1))  # can help as DOCUMENTATION

# --- ALWAYS use column or row vectors, not rank 1 arrays
# OR reshape:
a.reshape((5,1))

# A trick when you want to flatten a matrix X of shape (a,b,c,d) 
# to a matrix X_flatten of shape (b ∗ c ∗ d, a) is to use:
X_flatten = X.reshape(X.shape[0], -1).T

## Many software bugs in deep learning 
## come from having matrix/vector dimensions that don't fit

(5,)
[-0.64059518  0.44481699  0.96361191  0.02271607  3.31552572]
12.52999907266234

[[-1.04325495]
 [ 1.44211879]
 [-0.48980482]
 [-0.54597879]
 [ 0.72110785]]
[[-1.04325495  1.44211879 -0.48980482 -0.54597879  0.72110785]]
[[ 1.0883809  -1.50449757  0.51099131  0.56959508 -0.75229934]
 [-1.50449757  2.07970659 -0.70635674 -0.78736627  1.03992318]
 [ 0.51099131 -0.70635674  0.23990876  0.26742305 -0.3532021 ]
 [ 0.56959508 -0.78736627  0.26742305  0.29809284 -0.39370959]
 [-0.75229934  1.03992318 -0.3532021  -0.39370959  0.51999653]]


NameError: name 'X' is not defined

# Best NN perfs = scale
  scale algorithms: very large NN (lots of hidden layers, of parameters, of connections)  
+ scale data: very large amount of data  
+ scale computation: CPU, GPU  
ex: switch from sigmoid (lrng becomes really slow at extremities) to relu  
 -> GD works much faster  
 (Neural Networks and Deep Learning - Semaine 1 - Why is Deep Learning taking off?)  
